
graph TD
    A{fd > 0} -->|NO| B{!store OD 'nl'}
    A --> |YES|C[NULL]
    B --> |YES|D[Check --> <a href=https://github.com/ELREKO/get_next_line/blob/main/doc/readbuf.mmd> store = readbuf </a> ]


